name: Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Instalar dependências
      run: |
        npm ci

    - name: Criar ficheiro de environment com secrets
      run: |
        cat <<EOF > production_env.json
        {
            "name": "production_env",
            "values": [
                { "key": "login_email", "value": "${{ secrets.API_EMAIL }}", "type": "default" },
                { "key": "login_password", "value": "${{ secrets.API_PASSWORD }}", "type": "default" },
                { "key": "base_url", "value": "${{ secrets.API_BASE_URL }}", "type": "default" }
            ]
        }
        EOF

    - name: Carregar variáveis de ambiente
      run: |
        node setup-env.js

    - name: Correr testes Newman
      run: |
        npm run test
      continue-on-error: true

    - name: Guardar relatório como artefacto
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: NEWMAN_MINHA_API/reports/report.html
