name: Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Instalar dependências
      run: |
        cd NEWMAN_MINHA_API
        npm ci

    - name: Correr testes Newman
      run: |
        cd NEWMAN_MINHA_API
        npm run test

    - name: Guardar relatório como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: NEWMAN_MINHA_API/reports/report.html
